version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: otani
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: otani
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"